//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Data.UsuarioIntranetService1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IUsuarioIntranetService", Namespace="http://tempuri.org/")]
    public partial class UsuarioIntranetService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback CountUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsuariosFilterOperationCompleted;
        
        private System.Threading.SendOrPostCallback CountUsuariosFilterOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UsuarioIntranetService() {
            this.Url = global::Data.Properties.Settings.Default.Data_UsuarioIntranetService1_UsuarioIntranetService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUsuariosCompletedEventHandler GetUsuariosCompleted;
        
        /// <remarks/>
        public event CountUsuariosCompletedEventHandler CountUsuariosCompleted;
        
        /// <remarks/>
        public event GetUsuarioCompletedEventHandler GetUsuarioCompleted;
        
        /// <remarks/>
        public event GetUsuariosFilterCompletedEventHandler GetUsuariosFilterCompleted;
        
        /// <remarks/>
        public event CountUsuariosFilterCompletedEventHandler CountUsuariosFilterCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUsuarioIntranetService/GetUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PRODUCE.NETLOGIN.Response")]
        public UsuarioIntranetExtendidoResponse[] GetUsuarios(int idRol, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idRolSpecified, int idAplicacion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idAplicacionSpecified, int pageIndex, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageIndexSpecified, int pageSize, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageSizeSpecified) {
            object[] results = this.Invoke("GetUsuarios", new object[] {
                        idRol,
                        idRolSpecified,
                        idAplicacion,
                        idAplicacionSpecified,
                        pageIndex,
                        pageIndexSpecified,
                        pageSize,
                        pageSizeSpecified});
            return ((UsuarioIntranetExtendidoResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsuariosAsync(int idRol, bool idRolSpecified, int idAplicacion, bool idAplicacionSpecified, int pageIndex, bool pageIndexSpecified, int pageSize, bool pageSizeSpecified) {
            this.GetUsuariosAsync(idRol, idRolSpecified, idAplicacion, idAplicacionSpecified, pageIndex, pageIndexSpecified, pageSize, pageSizeSpecified, null);
        }
        
        /// <remarks/>
        public void GetUsuariosAsync(int idRol, bool idRolSpecified, int idAplicacion, bool idAplicacionSpecified, int pageIndex, bool pageIndexSpecified, int pageSize, bool pageSizeSpecified, object userState) {
            if ((this.GetUsuariosOperationCompleted == null)) {
                this.GetUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsuariosOperationCompleted);
            }
            this.InvokeAsync("GetUsuarios", new object[] {
                        idRol,
                        idRolSpecified,
                        idAplicacion,
                        idAplicacionSpecified,
                        pageIndex,
                        pageIndexSpecified,
                        pageSize,
                        pageSizeSpecified}, this.GetUsuariosOperationCompleted, userState);
        }
        
        private void OnGetUsuariosOperationCompleted(object arg) {
            if ((this.GetUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsuariosCompleted(this, new GetUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUsuarioIntranetService/CountUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CountUsuarios(int idRol, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idRolSpecified, int idAplicacion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idAplicacionSpecified, out int CountUsuariosResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CountUsuariosResultSpecified) {
            object[] results = this.Invoke("CountUsuarios", new object[] {
                        idRol,
                        idRolSpecified,
                        idAplicacion,
                        idAplicacionSpecified});
            CountUsuariosResult = ((int)(results[0]));
            CountUsuariosResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void CountUsuariosAsync(int idRol, bool idRolSpecified, int idAplicacion, bool idAplicacionSpecified) {
            this.CountUsuariosAsync(idRol, idRolSpecified, idAplicacion, idAplicacionSpecified, null);
        }
        
        /// <remarks/>
        public void CountUsuariosAsync(int idRol, bool idRolSpecified, int idAplicacion, bool idAplicacionSpecified, object userState) {
            if ((this.CountUsuariosOperationCompleted == null)) {
                this.CountUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCountUsuariosOperationCompleted);
            }
            this.InvokeAsync("CountUsuarios", new object[] {
                        idRol,
                        idRolSpecified,
                        idAplicacion,
                        idAplicacionSpecified}, this.CountUsuariosOperationCompleted, userState);
        }
        
        private void OnCountUsuariosOperationCompleted(object arg) {
            if ((this.CountUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CountUsuariosCompleted(this, new CountUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUsuarioIntranetService/GetUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UsuarioIntranetExtendidoResponse GetUsuario(int codigoTrabajador, [System.Xml.Serialization.XmlIgnoreAttribute()] bool codigoTrabajadorSpecified, int idRol, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idRolSpecified, int idAplicacion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idAplicacionSpecified) {
            object[] results = this.Invoke("GetUsuario", new object[] {
                        codigoTrabajador,
                        codigoTrabajadorSpecified,
                        idRol,
                        idRolSpecified,
                        idAplicacion,
                        idAplicacionSpecified});
            return ((UsuarioIntranetExtendidoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsuarioAsync(int codigoTrabajador, bool codigoTrabajadorSpecified, int idRol, bool idRolSpecified, int idAplicacion, bool idAplicacionSpecified) {
            this.GetUsuarioAsync(codigoTrabajador, codigoTrabajadorSpecified, idRol, idRolSpecified, idAplicacion, idAplicacionSpecified, null);
        }
        
        /// <remarks/>
        public void GetUsuarioAsync(int codigoTrabajador, bool codigoTrabajadorSpecified, int idRol, bool idRolSpecified, int idAplicacion, bool idAplicacionSpecified, object userState) {
            if ((this.GetUsuarioOperationCompleted == null)) {
                this.GetUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsuarioOperationCompleted);
            }
            this.InvokeAsync("GetUsuario", new object[] {
                        codigoTrabajador,
                        codigoTrabajadorSpecified,
                        idRol,
                        idRolSpecified,
                        idAplicacion,
                        idAplicacionSpecified}, this.GetUsuarioOperationCompleted, userState);
        }
        
        private void OnGetUsuarioOperationCompleted(object arg) {
            if ((this.GetUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsuarioCompleted(this, new GetUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUsuarioIntranetService/GetUsuariosFilter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PRODUCE.NETLOGIN.Response")]
        public UsuarioIntranetExtendidoResponse[] GetUsuariosFilter([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UsuarioIntranetExtendidoRequest filter, int idRol, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idRolSpecified, int idAplicacion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idAplicacionSpecified, int pageIndex, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageIndexSpecified, int pageSize, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageSizeSpecified) {
            object[] results = this.Invoke("GetUsuariosFilter", new object[] {
                        filter,
                        idRol,
                        idRolSpecified,
                        idAplicacion,
                        idAplicacionSpecified,
                        pageIndex,
                        pageIndexSpecified,
                        pageSize,
                        pageSizeSpecified});
            return ((UsuarioIntranetExtendidoResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsuariosFilterAsync(UsuarioIntranetExtendidoRequest filter, int idRol, bool idRolSpecified, int idAplicacion, bool idAplicacionSpecified, int pageIndex, bool pageIndexSpecified, int pageSize, bool pageSizeSpecified) {
            this.GetUsuariosFilterAsync(filter, idRol, idRolSpecified, idAplicacion, idAplicacionSpecified, pageIndex, pageIndexSpecified, pageSize, pageSizeSpecified, null);
        }
        
        /// <remarks/>
        public void GetUsuariosFilterAsync(UsuarioIntranetExtendidoRequest filter, int idRol, bool idRolSpecified, int idAplicacion, bool idAplicacionSpecified, int pageIndex, bool pageIndexSpecified, int pageSize, bool pageSizeSpecified, object userState) {
            if ((this.GetUsuariosFilterOperationCompleted == null)) {
                this.GetUsuariosFilterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsuariosFilterOperationCompleted);
            }
            this.InvokeAsync("GetUsuariosFilter", new object[] {
                        filter,
                        idRol,
                        idRolSpecified,
                        idAplicacion,
                        idAplicacionSpecified,
                        pageIndex,
                        pageIndexSpecified,
                        pageSize,
                        pageSizeSpecified}, this.GetUsuariosFilterOperationCompleted, userState);
        }
        
        private void OnGetUsuariosFilterOperationCompleted(object arg) {
            if ((this.GetUsuariosFilterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsuariosFilterCompleted(this, new GetUsuariosFilterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUsuarioIntranetService/CountUsuariosFilter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CountUsuariosFilter([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UsuarioIntranetExtendidoRequest filter, int idRol, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idRolSpecified, int idAplicacion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idAplicacionSpecified, out int CountUsuariosFilterResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CountUsuariosFilterResultSpecified) {
            object[] results = this.Invoke("CountUsuariosFilter", new object[] {
                        filter,
                        idRol,
                        idRolSpecified,
                        idAplicacion,
                        idAplicacionSpecified});
            CountUsuariosFilterResult = ((int)(results[0]));
            CountUsuariosFilterResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void CountUsuariosFilterAsync(UsuarioIntranetExtendidoRequest filter, int idRol, bool idRolSpecified, int idAplicacion, bool idAplicacionSpecified) {
            this.CountUsuariosFilterAsync(filter, idRol, idRolSpecified, idAplicacion, idAplicacionSpecified, null);
        }
        
        /// <remarks/>
        public void CountUsuariosFilterAsync(UsuarioIntranetExtendidoRequest filter, int idRol, bool idRolSpecified, int idAplicacion, bool idAplicacionSpecified, object userState) {
            if ((this.CountUsuariosFilterOperationCompleted == null)) {
                this.CountUsuariosFilterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCountUsuariosFilterOperationCompleted);
            }
            this.InvokeAsync("CountUsuariosFilter", new object[] {
                        filter,
                        idRol,
                        idRolSpecified,
                        idAplicacion,
                        idAplicacionSpecified}, this.CountUsuariosFilterOperationCompleted, userState);
        }
        
        private void OnCountUsuariosFilterOperationCompleted(object arg) {
            if ((this.CountUsuariosFilterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CountUsuariosFilterCompleted(this, new CountUsuariosFilterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PRODUCE.NETLOGIN.Response")]
    public partial class UsuarioIntranetExtendidoResponse {
        
        private string anexoField;
        
        private string apellidosField;
        
        private int codigodependenciaField;
        
        private bool codigodependenciaFieldSpecified;
        
        private int codigotrabajadorField;
        
        private bool codigotrabajadorFieldSpecified;
        
        private string dniField;
        
        private int idaplicacionField;
        
        private bool idaplicacionFieldSpecified;
        
        private int idrolField;
        
        private bool idrolFieldSpecified;
        
        private string loginField;
        
        private string nombrecompletoField;
        
        private string nombrerolField;
        
        private string nombresField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string anexo {
            get {
                return this.anexoField;
            }
            set {
                this.anexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
            }
        }
        
        /// <remarks/>
        public int codigodependencia {
            get {
                return this.codigodependenciaField;
            }
            set {
                this.codigodependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigodependenciaSpecified {
            get {
                return this.codigodependenciaFieldSpecified;
            }
            set {
                this.codigodependenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int codigotrabajador {
            get {
                return this.codigotrabajadorField;
            }
            set {
                this.codigotrabajadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigotrabajadorSpecified {
            get {
                return this.codigotrabajadorFieldSpecified;
            }
            set {
                this.codigotrabajadorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
            }
        }
        
        /// <remarks/>
        public int idaplicacion {
            get {
                return this.idaplicacionField;
            }
            set {
                this.idaplicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idaplicacionSpecified {
            get {
                return this.idaplicacionFieldSpecified;
            }
            set {
                this.idaplicacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int idrol {
            get {
                return this.idrolField;
            }
            set {
                this.idrolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idrolSpecified {
            get {
                return this.idrolFieldSpecified;
            }
            set {
                this.idrolFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombrecompleto {
            get {
                return this.nombrecompletoField;
            }
            set {
                this.nombrecompletoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombrerol {
            get {
                return this.nombrerolField;
            }
            set {
                this.nombrerolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PRODUCE.NETLOGIN.Request")]
    public partial class UsuarioIntranetExtendidoRequest {
        
        private string anexoField;
        
        private string apellidosField;
        
        private int codigodependenciaField;
        
        private bool codigodependenciaFieldSpecified;
        
        private int codigotrabajadorField;
        
        private bool codigotrabajadorFieldSpecified;
        
        private string dniField;
        
        private int idaplicacionField;
        
        private bool idaplicacionFieldSpecified;
        
        private int idrolField;
        
        private bool idrolFieldSpecified;
        
        private string loginField;
        
        private string nombrecompletoField;
        
        private string nombrerolField;
        
        private string nombresField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string anexo {
            get {
                return this.anexoField;
            }
            set {
                this.anexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
            }
        }
        
        /// <remarks/>
        public int codigodependencia {
            get {
                return this.codigodependenciaField;
            }
            set {
                this.codigodependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigodependenciaSpecified {
            get {
                return this.codigodependenciaFieldSpecified;
            }
            set {
                this.codigodependenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int codigotrabajador {
            get {
                return this.codigotrabajadorField;
            }
            set {
                this.codigotrabajadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigotrabajadorSpecified {
            get {
                return this.codigotrabajadorFieldSpecified;
            }
            set {
                this.codigotrabajadorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
            }
        }
        
        /// <remarks/>
        public int idaplicacion {
            get {
                return this.idaplicacionField;
            }
            set {
                this.idaplicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idaplicacionSpecified {
            get {
                return this.idaplicacionFieldSpecified;
            }
            set {
                this.idaplicacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int idrol {
            get {
                return this.idrolField;
            }
            set {
                this.idrolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idrolSpecified {
            get {
                return this.idrolFieldSpecified;
            }
            set {
                this.idrolFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombrecompleto {
            get {
                return this.nombrecompletoField;
            }
            set {
                this.nombrecompletoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombrerol {
            get {
                return this.nombrerolField;
            }
            set {
                this.nombrerolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUsuariosCompletedEventHandler(object sender, GetUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioIntranetExtendidoResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioIntranetExtendidoResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CountUsuariosCompletedEventHandler(object sender, CountUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CountUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int CountUsuariosResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool CountUsuariosResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUsuarioCompletedEventHandler(object sender, GetUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioIntranetExtendidoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioIntranetExtendidoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUsuariosFilterCompletedEventHandler(object sender, GetUsuariosFilterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsuariosFilterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsuariosFilterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioIntranetExtendidoResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioIntranetExtendidoResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CountUsuariosFilterCompletedEventHandler(object sender, CountUsuariosFilterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountUsuariosFilterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CountUsuariosFilterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int CountUsuariosFilterResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool CountUsuariosFilterResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591