//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public long Id { get; set; }
        public long id_encuesta { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string accion { get; set; }
    
        public virtual Encuesta Encuesta { get; set; }
    }
}
