//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AñoBase
    {
        public long Id { get; set; }
        public long id_establecimiento { get; set; }
        public long id_ciiu { get; set; }
        public long id_linea_producto { get; set; }
        public long id_unidad_medida { get; set; }
        public decimal produccion_anual { get; set; }
        public decimal valor_produccion { get; set; }
        public decimal precio { get; set; }
        public decimal estado { get; set; }
    
        public virtual Establecimiento CAT_ESTABLECIMIENTO { get; set; }
        public virtual Ciiu CAT_CIIU { get; set; }
        public virtual LineaProducto CAT_LINEA_PRODUCTO { get; set; }
        public virtual UnidadMedida CAT_UNIDAD_MEDIDA { get; set; }
    }
}
