//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AñoBase
    {
        public long Id { get; set; }
        public long id_establecimiento { get; set; }
        public long id_ciiu { get; set; }
        public Nullable<long> id_linea_producto { get; set; }
        public Nullable<long> id_unidad_medida { get; set; }
        public decimal produccion_anual { get; set; }
        public decimal valor_produccion { get; set; }
        public decimal precio { get; set; }
        public decimal estado { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    
        public virtual Establecimiento CAT_ESTABLECIMIENTO { get; set; }
        public virtual Ciiu CAT_CIIU { get; set; }
        public virtual LineaProducto CAT_LINEA_PRODUCTO { get; set; }
        public virtual UnidadMedida CAT_UNIDAD_MEDIDA { get; set; }
    }
}
