//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciiu
    {
        public Ciiu()
        {
            this.LineasProducto = new HashSet<LineaProducto>();
            this.Establecimientos = new HashSet<CiiuEstablecimiento>();
            this.DAT_VALOR_PROD_MENSUAL = new HashSet<ValorProduccion>();
            this.DAT_VENTAS_PAIS_EXTRANJERO = new HashSet<VentasPaisExtranjero>();
            this.DAT_IPM_IPP = new HashSet<IpmIpp>();
            this.CAT_ANIO_BASE = new HashSet<AñoBase>();
            this.CAT_ESTAB_ANALISTA = new HashSet<EstablecimientoAnalista>();
            this.DAT_ENCUESTA_ANALISTA = new HashSet<EncuestaAnalista>();
        }
    
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public decimal Estado { get; set; }
        public decimal Revision { get; set; }
        public long Id { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<long> id_metodo_calculo { get; set; }
        public long sub_sector { get; set; }
        public long rubro { get; set; }
    
        public virtual ICollection<LineaProducto> LineasProducto { get; set; }
        public virtual ICollection<CiiuEstablecimiento> Establecimientos { get; set; }
        public virtual ICollection<ValorProduccion> DAT_VALOR_PROD_MENSUAL { get; set; }
        public virtual ICollection<VentasPaisExtranjero> DAT_VENTAS_PAIS_EXTRANJERO { get; set; }
        public virtual ICollection<IpmIpp> DAT_IPM_IPP { get; set; }
        public virtual MetodoCalculo CAT_METODO_CALCULO { get; set; }
        public virtual ICollection<AñoBase> CAT_ANIO_BASE { get; set; }
        public virtual ICollection<EstablecimientoAnalista> CAT_ESTAB_ANALISTA { get; set; }
        public virtual ICollection<EncuestaAnalista> DAT_ENCUESTA_ANALISTA { get; set; }
    }
}
