//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciiu
    {
        public Ciiu()
        {
            this.LineasProducto = new HashSet<LineaProducto>();
            this.Establecimientos = new HashSet<Establecimiento>();
            this.CAT_VALOR_PROD_MENSUAL = new HashSet<ValorProduccion>();
            this.CAT_VENTAS_PAIS_EXTRANJERO = new HashSet<VentasPaisExtranjero>();
            this.CAT_IPM_IPP = new HashSet<IpmIpp>();
        }
    
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public decimal Estado { get; set; }
        public string Revision { get; set; }
        public long Id { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<long> id_metodo_calculo { get; set; }
        public long sub_sector { get; set; }
        public long rubro { get; set; }
    
        public virtual ICollection<LineaProducto> LineasProducto { get; set; }
        public virtual ICollection<Establecimiento> Establecimientos { get; set; }
        public virtual ICollection<ValorProduccion> CAT_VALOR_PROD_MENSUAL { get; set; }
        public virtual ICollection<VentasPaisExtranjero> CAT_VENTAS_PAIS_EXTRANJERO { get; set; }
        public virtual ICollection<IpmIpp> CAT_IPM_IPP { get; set; }
        public virtual MetodoCalculo CAT_METODO_CALCULO { get; set; }
    }
}
