//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public long Id { get; set; }
        public decimal Estado { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Anexo { get; set; }
        public string Celular { get; set; }
        public long IdEstablecimiento { get; set; }
        public Nullable<long> IdCargo { get; set; }
        public Nullable<decimal> IdUsuario { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
