//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaEstadistica : Encuesta
    {
        public EncuestaEstadistica()
        {
            this.CAT_VALOR_PROD_MENSUAL = new HashSet<ValorProduccion>();
        }
    
        public Nullable<System.DateTime> fecha_validacion { get; set; }
    
        public virtual TrabajadoresDiasTrabajados TrabajadoresDiasTrabajados { get; set; }
        public virtual VentasProductosEstablecimientos VentasProductosEstablecimiento { get; set; }
        public virtual VolumenProduccion VolumenProduccionMensual { get; set; }
        public virtual ICollection<ValorProduccion> CAT_VALOR_PROD_MENSUAL { get; set; }
        public virtual FactorProducccion FactorProduccion { get; set; }
    }
}
