//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaEmpresarial : Encuesta
    {
        public EncuestaEmpresarial()
        {
            this.Preguntas = new HashSet<Pregunta>();
            this.CAT_PREGUNTA = new HashSet<Pregunta>();
        }
    
    
        public virtual ICollection<Pregunta> Preguntas { get; set; }
        public virtual ICollection<Pregunta> CAT_PREGUNTA { get; set; }
    }
}
