//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaAnalista
    {
        public long Id { get; set; }
        public decimal orden { get; set; }
        public long id_encuesta { get; set; }
        public decimal id_analista { get; set; }
        public long id_ciiu { get; set; }
        public decimal estado { get; set; }
        public decimal current { get; set; }
    
        public virtual Ciiu CAT_CIIU { get; set; }
        public virtual Encuesta DAT_ENCUESTA { get; set; }
        public virtual Usuario SEG_USUARIO { get; set; }
    }
}
