//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaEstadistica : Encuesta
    {
        public EncuestaEstadistica()
        {
            this.DAT_VALOR_PROD_MENSUAL = new HashSet<ValorProduccion>();
        }
    
        public Nullable<System.DateTime> fecha_validacion { get; set; }
        public decimal actualizacion { get; set; }
    
        public virtual TrabajadoresDiasTrabajados TrabajadoresDiasTrabajados { get; set; }
        public virtual VentasProductosEstablecimientos VentasProductosEstablecimiento { get; set; }
        public virtual VolumenProduccion VolumenProduccionMensual { get; set; }
        public virtual ICollection<ValorProduccion> DAT_VALOR_PROD_MENSUAL { get; set; }
        public virtual FactorProducccion FactorProduccion { get; set; }
    }
}
