//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaEmpresarial : Encuesta
    {
        public EncuestaEmpresarial()
        {
            this.Preguntas = new HashSet<Pregunta>();
            this.DAT_PREGUNTA = new HashSet<Pregunta>();
        }
    
    
        public virtual ICollection<Pregunta> Preguntas { get; set; }
        public virtual ICollection<Pregunta> DAT_PREGUNTA { get; set; }
    }
}
