//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstablecimientoAnalista
    {
        public long Id { get; set; }
        public decimal orden { get; set; }
        public long id_establecimiento { get; set; }
        public decimal id_analista { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public long id_ciiu { get; set; }
    
        public virtual Establecimiento CAT_ESTABLECIMIENTO { get; set; }
        public virtual Usuario SEG_USUARIO { get; set; }
        public virtual Ciiu CAT_CIIU { get; set; }
    }
}
