//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorProducccion
    {
        public FactorProducccion()
        {
            this.CAT_FACTOR1 = new HashSet<Factor>();
        }
    
        public long Identificador { get; set; }
        public short ProduccionNormal { get; set; }
        public short Incremento { get; set; }
        public short Decrecimiento { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string OtroFactor { get; set; }
    
        public virtual EncuestaEstadistica Encuesta { get; set; }
        public virtual ICollection<Factor> CAT_FACTOR1 { get; set; }
    }
}
