//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        public Factor()
        {
            this.CAT_FACTOR_PRODUCCION1 = new HashSet<FactorProducccion>();
        }
    
        public long Id { get; set; }
        public decimal Tipo { get; set; }
        public string Nombre { get; set; }
        public decimal Estado { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    
        public virtual ICollection<FactorProducccion> CAT_FACTOR_PRODUCCION1 { get; set; }
    }
}
