//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        public Factor()
        {
            this.DAT_FACTOR_PRODUCCION1 = new HashSet<FactorProducccion>();
        }
    
        public long Id { get; set; }
        public decimal Tipo { get; set; }
        public string Nombre { get; set; }
        public decimal Estado { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    
        public virtual ICollection<FactorProducccion> DAT_FACTOR_PRODUCCION1 { get; set; }
    }
}
