//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportacionHarinaTrigo
    {
        public long Id { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal cif_usd { get; set; }
        public decimal cif_s { get; set; }
        public decimal estado { get; set; }
    }
}
