//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaProductoUnidadMedida
    {
        public long Id { get; set; }
        public Nullable<long> id_unidad_conversion { get; set; }
        public decimal factor_conversion { get; set; }
        public Nullable<long> id_unidad_medida { get; set; }
        public Nullable<long> id_linea_producto { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    
        public virtual UnidadMedida UnidadConversion { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        public virtual LineaProducto LineaProducto { get; set; }
    }
}
