//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaProducto
    {
        public LineaProducto()
        {
            this.LineasProductoEstablecimiento = new HashSet<LineaProductoEstablecimiento>();
            this.MateriasPropia = new HashSet<MateriaPropia>();
            this.MateriaTercero = new HashSet<MateriaTerceros>();
            this.LineasProductoUnidadMedida = new HashSet<LineaProductoUnidadMedida>();
            this.CAT_ANIO_BASE = new HashSet<AñoBase>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public decimal Estado { get; set; }
        public long IdCiiu { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    
        public virtual Ciiu Ciiu { get; set; }
        public virtual ICollection<LineaProductoEstablecimiento> LineasProductoEstablecimiento { get; set; }
        public virtual ICollection<MateriaPropia> MateriasPropia { get; set; }
        public virtual ICollection<MateriaTerceros> MateriaTercero { get; set; }
        public virtual ICollection<LineaProductoUnidadMedida> LineasProductoUnidadMedida { get; set; }
        public virtual ICollection<AñoBase> CAT_ANIO_BASE { get; set; }
    }
}
