//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaProductoUnidadMedida
    {
        public long Id { get; set; }
        public Nullable<long> id_unidad_conversion { get; set; }
        public decimal factor_conversion { get; set; }
        public Nullable<long> id_unidad_medida { get; set; }
        public Nullable<long> id_linea_producto { get; set; }
    
        public virtual UnidadMedida UnidadConversion { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        public virtual LineaProducto LineaProducto { get; set; }
    }
}
