//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaTerceros
    {
        public long Id { get; set; }
        public long IdLineaProducto { get; set; }
        public long IdUnidadMedida { get; set; }
        public string UnidadProduccion { get; set; }
        public long IdVolumenProduccion { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string justificacion_produccion { get; set; }
    
        public virtual LineaProducto LineaProducto { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        public virtual VolumenProduccion VolumenProduccion { get; set; }
    }
}
