//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaPropia
    {
        public long Id { get; set; }
        public long IdLineaProducto { get; set; }
        public long IdUnidadMedida { get; set; }
        public string JustificacionValorUnitario { get; set; }
        public string JustificacionProduccion { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public Nullable<decimal> Existencia { get; set; }
        public Nullable<decimal> Produccion { get; set; }
        public Nullable<decimal> OtrosIngresos { get; set; }
        public Nullable<decimal> VentasPais { get; set; }
        public Nullable<decimal> VentasExtranjero { get; set; }
        public Nullable<decimal> OtrasSalidas { get; set; }
        public Nullable<long> IdVolumenProduccion { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string justificacion_venta_pais { get; set; }
        public string justificacion_venta_extranjero { get; set; }
    
        public virtual LineaProducto LineaProducto { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        public virtual VolumenProduccion VolumenProduccion { get; set; }
    }
}
