//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodoCalculo
    {
        public MetodoCalculo()
        {
            this.CAT_CIIU = new HashSet<Ciiu>();
        }
    
        public long Id { get; set; }
        public string nombre { get; set; }
        public decimal estado { get; set; }
        public decimal registro_obligatorio { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    
        public virtual ICollection<Ciiu> CAT_CIIU { get; set; }
    }
}
