//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrizacionEnvio
    {
        public long Id { get; set; }
        public string tipo_encuesta { get; set; }
        public string mensaje { get; set; }
        public System.DateTime comienzo { get; set; }
        public long envio_1 { get; set; }
        public long envio_2 { get; set; }
        public decimal estado { get; set; }
        public string frecuencia { get; set; }
    }
}
