//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrizacionEnvio
    {
        public long Id { get; set; }
        public string tipo_encuesta { get; set; }
        public string mensaje { get; set; }
        public System.DateTime comienzo { get; set; }
        public long envio_1 { get; set; }
        public long envio_2 { get; set; }
        public decimal estado { get; set; }
        public string frecuencia { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    }
}
