//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosibleRespuesta
    {
        public PosibleRespuesta()
        {
            this.Valores = new HashSet<Valor>();
        }
    
        public long Id { get; set; }
        public decimal TipoPosibleRespuesta { get; set; }
        public long IdPregunta { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
        public virtual ICollection<Valor> Valores { get; set; }
    }
}
