//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosibleRespuesta
    {
        public PosibleRespuesta()
        {
            this.Valores = new HashSet<Valor>();
        }
    
        public long Id { get; set; }
        public decimal TipoPosibleRespuesta { get; set; }
        public long IdPregunta { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
        public virtual ICollection<Valor> Valores { get; set; }
    }
}
