//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        public Pregunta()
        {
            this.PosiblesRespuestas = new HashSet<PosibleRespuesta>();
            this.Valores = new HashSet<Valor>();
        }
    
        public long Id { get; set; }
        public string Texto { get; set; }
        public decimal Estado { get; set; }
        public Nullable<System.DateTime> Comienza { get; set; }
        public Nullable<short> Intervalo { get; set; }
        public Nullable<long> IdEncuestaEmpresarial { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public short orden { get; set; }
        public Nullable<decimal> todas_alternativas_oblig { get; set; }
    
        public virtual ICollection<PosibleRespuesta> PosiblesRespuestas { get; set; }
        public virtual ICollection<Valor> Valores { get; set; }
        public virtual EncuestaEmpresarial Encuesta { get; set; }
        public virtual EncuestaEmpresarial DAT_ENCUESTA_EMPRESARIAL { get; set; }
    }
}
