//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public long Estado { get; set; }
    
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
