//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCambio
    {
        public long Id { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal tipo_cambio_ventas { get; set; }
        public decimal tipo_cambio_compra { get; set; }
        public decimal estado { get; set; }
    }
}
