//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajadoresDiasTrabajados
    {
        public long Identificador { get; set; }
        public Nullable<decimal> DiasTrabajados { get; set; }
        public Nullable<decimal> TrabajadoresProduccion { get; set; }
        public Nullable<decimal> AdministrativosPlanta { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    
        public virtual EncuestaEstadistica Encuesta { get; set; }
    }
}
