//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajadoresDiasTrabajados
    {
        public long Identificador { get; set; }
        public Nullable<decimal> DiasTrabajados { get; set; }
        public Nullable<decimal> TrabajadoresProduccion { get; set; }
        public Nullable<decimal> AdministrativosPlanta { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    
        public virtual EncuestaEstadistica Encuesta { get; set; }
    }
}
