//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadMedida
    {
        public UnidadMedida()
        {
            this.MateriasPropias = new HashSet<MateriaPropia>();
            this.MateriasTerceros = new HashSet<MateriaTerceros>();
            this.AsUnidadConversion = new HashSet<LineaProductoUnidadMedida>();
            this.LineasProductoUnidadMedida = new HashSet<LineaProductoUnidadMedida>();
            this.CAT_ANIO_BASE = new HashSet<AñoBase>();
        }
    
        public string Descripcion { get; set; }
        public string Abreviatura { get; set; }
        public long Id { get; set; }
        public decimal Estado { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    
        public virtual ICollection<MateriaPropia> MateriasPropias { get; set; }
        public virtual ICollection<MateriaTerceros> MateriasTerceros { get; set; }
        public virtual ICollection<LineaProductoUnidadMedida> AsUnidadConversion { get; set; }
        public virtual ICollection<LineaProductoUnidadMedida> LineasProductoUnidadMedida { get; set; }
        public virtual ICollection<AñoBase> CAT_ANIO_BASE { get; set; }
    }
}
