//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.EncuestasAsInformante = new HashSet<Encuesta>();
            this.EstablecimientosInformante = new HashSet<Establecimiento>();
            this.Roles = new HashSet<Rol>();
            this.CAT_ESTAB_ANALISTA = new HashSet<EstablecimientoAnalista>();
            this.DAT_ENCUESTA_ANALISTA = new HashSet<EncuestaAnalista>();
        }
    
        public decimal Identificador { get; set; }
        public string Login { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
    
        public virtual ICollection<Encuesta> EncuestasAsInformante { get; set; }
        public virtual ICollection<Establecimiento> EstablecimientosInformante { get; set; }
        public virtual ICollection<Rol> Roles { get; set; }
        public virtual ICollection<EstablecimientoAnalista> CAT_ESTAB_ANALISTA { get; set; }
        public virtual ICollection<EncuestaAnalista> DAT_ENCUESTA_ANALISTA { get; set; }
    }
}
