//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValorProduccion
    {
        public long Id { get; set; }
        public Nullable<decimal> ProductosMateriaPropia { get; set; }
        public Nullable<decimal> ProductosMateriaTerceros { get; set; }
        public long id_ciiu { get; set; }
        public long id_encuesta { get; set; }
        public string justificacion_materia_prop { get; set; }
        public string justificacion_materia_terc { get; set; }
    
        public virtual Ciiu CAT_CIIU { get; set; }
        public virtual EncuestaEstadistica CAT_ENCUESTA_ESTADISTICA { get; set; }
    }
}
