//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValorProduccion
    {
        public long Id { get; set; }
        public Nullable<decimal> ProductosMateriaPropia { get; set; }
        public Nullable<decimal> ProductosMateriaTerceros { get; set; }
        public long id_ciiu { get; set; }
        public long id_encuesta { get; set; }
        public string justificacion_materia_prop { get; set; }
        public string justificacion_materia_terc { get; set; }
    
        public virtual Ciiu CAT_CIIU { get; set; }
        public virtual EncuestaEstadistica DAT_ENCUESTA_ESTADISTICA { get; set; }
    }
}
