//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valor
    {
        public long Id { get; set; }
        public string Texto { get; set; }
        public Nullable<decimal> Numero { get; set; }
        public decimal Estado { get; set; }
        public long IdPosibleRespuesta { get; set; }
        public Nullable<long> IdPregunta { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public decimal es_personalizado { get; set; }
        public string texto_personalizado { get; set; }
    
        public virtual PosibleRespuesta PosibleRespuesta { get; set; }
        public virtual Pregunta Pregunta { get; set; }
    }
}
