//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasProductosEstablecimientos
    {
        public VentasProductosEstablecimientos()
        {
            this.VentasServicioManufactura = new HashSet<VentasServicioManufactura>();
            this.DAT_VENTAS_PAIS_EXTRANJERO = new HashSet<VentasPaisExtranjero>();
        }
    
        public long Identificador { get; set; }
        public short brindo_servicios { get; set; }
    
        public virtual ICollection<VentasServicioManufactura> VentasServicioManufactura { get; set; }
        public virtual EncuestaEstadistica Encuesta { get; set; }
        public virtual ICollection<VentasPaisExtranjero> DAT_VENTAS_PAIS_EXTRANJERO { get; set; }
    }
}
