//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasServicioManufactura
    {
        public long Id { get; set; }
        public long IdVentaProductoestablecimiento { get; set; }
        public Nullable<decimal> venta { get; set; }
        public string ciiu { get; set; }
        public string detalle { get; set; }
        public Nullable<decimal> venta_extranjero { get; set; }
        public string justificacion_venta_pais { get; set; }
        public string justificacion_venta_ext { get; set; }
    
        public virtual VentasProductosEstablecimientos VentaProductoEstablecimiento { get; set; }
    }
}
