//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasPaisExtranjero
    {
        public long Id { get; set; }
        public Nullable<decimal> VentaPais { get; set; }
        public Nullable<decimal> VentaExtranjero { get; set; }
        public long id_ciiu { get; set; }
        public long id_ventas_producto { get; set; }
        public string justificacion_venta_pais { get; set; }
        public string justificacion_venta_ext { get; set; }
    
        public virtual Ciiu CAT_CIIU { get; set; }
        public virtual VentasProductosEstablecimientos DAT_VENTAS_PROD_ESTAB { get; set; }
    }
}
