//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasServicioManufactura
    {
        public long Id { get; set; }
        public long IdVentaProductoestablecimiento { get; set; }
        public Nullable<decimal> venta { get; set; }
        public string ciiu { get; set; }
        public string detalle { get; set; }
        public Nullable<decimal> venta_extranjero { get; set; }
        public string justificacion_venta_pais { get; set; }
        public string justificacion_venta_ext { get; set; }
    
        public virtual VentasProductosEstablecimientos VentaProductoEstablecimiento { get; set; }
    }
}
