//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasPaisExtranjero
    {
        public long Id { get; set; }
        public Nullable<decimal> VentaPais { get; set; }
        public Nullable<decimal> VentaExtranjero { get; set; }
        public long id_ciiu { get; set; }
        public long id_ventas_producto { get; set; }
        public string justificacion_venta_pais { get; set; }
        public string justificacion_venta_ext { get; set; }
    
        public virtual Ciiu CAT_CIIU { get; set; }
        public virtual VentasProductosEstablecimientos CAT_VENTAS_PROD_ESTAB { get; set; }
    }
}
