//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProcentajeEncuestaExtadistica
    {
        public long id_encuesta { get; set; }
        public decimal estado_encuesta { get; set; }
        public long id_establecimiento { get; set; }
        public System.DateTime fecha { get; set; }
        public long id_ciiu { get; set; }
        public decimal id_analista { get; set; }
        public decimal estado_validacion { get; set; }
        public string codigo_ciiu { get; set; }
        public string nombre_ciiu { get; set; }
        public string login_analista { get; set; }
    }
}
