CREATE DATABASE UbigeoProduce
GO
USE UbigeoProduce
GO
CREATE TABLE UBIGEO(
	UBIGEO CHAR(6),
	DEPARTAMENTO VARCHAR(150),
	PROVINCIA VARCHAR(150),
	DISTRITO VARCHAR(150)
)


INSERT INTO UBIGEO VALUES('150101', 'LIMA', 'LIMA', 'LIMA')

INSERT INTO dbo.UBIGEO
SELECT u.[UBIGEO],
	 u.[DEPARTAMENTO],
	 u.[PROVINCIA],
	 u.[DISTRITO]
FROM [HVitarteBD].[dbo].[UBIGEO] u
WHERE len([UBIGEO]) = 6