//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplication.ServiceSunat {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HttpSistemasService", Namespace="http://tempuri.org/")]
    public partial class WCFSistemasService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarSunatProduccionParametroOperationCompleted;
        
        private System.Threading.SendOrPostCallback Validacion_SUNATOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WCFSistemasService() {
            this.Url = global::WebApplication.Properties.Settings.Default.WebApplication_ServiceSunat_WCFSistemasService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarSunatProduccionParametroCompletedEventHandler BuscarSunatProduccionParametroCompleted;
        
        /// <remarks/>
        public event Validacion_SUNATCompletedEventHandler Validacion_SUNATCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFSistemasService/BuscarSunatProduccionParametro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BuscarEmpresaResult BuscarSunatProduccionParametro([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ID_RUC) {
            object[] results = this.Invoke("BuscarSunatProduccionParametro", new object[] {
                        ID_RUC});
            return ((BuscarEmpresaResult)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarSunatProduccionParametroAsync(string ID_RUC) {
            this.BuscarSunatProduccionParametroAsync(ID_RUC, null);
        }
        
        /// <remarks/>
        public void BuscarSunatProduccionParametroAsync(string ID_RUC, object userState) {
            if ((this.BuscarSunatProduccionParametroOperationCompleted == null)) {
                this.BuscarSunatProduccionParametroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarSunatProduccionParametroOperationCompleted);
            }
            this.InvokeAsync("BuscarSunatProduccionParametro", new object[] {
                        ID_RUC}, this.BuscarSunatProduccionParametroOperationCompleted, userState);
        }
        
        private void OnBuscarSunatProduccionParametroOperationCompleted(object arg) {
            if ((this.BuscarSunatProduccionParametroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarSunatProduccionParametroCompleted(this, new BuscarSunatProduccionParametroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFSistemasService/Validacion_SUNAT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BuscarEmpresaResult Validacion_SUNAT([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ID_RUC) {
            object[] results = this.Invoke("Validacion_SUNAT", new object[] {
                        ID_RUC});
            return ((BuscarEmpresaResult)(results[0]));
        }
        
        /// <remarks/>
        public void Validacion_SUNATAsync(string ID_RUC) {
            this.Validacion_SUNATAsync(ID_RUC, null);
        }
        
        /// <remarks/>
        public void Validacion_SUNATAsync(string ID_RUC, object userState) {
            if ((this.Validacion_SUNATOperationCompleted == null)) {
                this.Validacion_SUNATOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidacion_SUNATOperationCompleted);
            }
            this.InvokeAsync("Validacion_SUNAT", new object[] {
                        ID_RUC}, this.Validacion_SUNATOperationCompleted, userState);
        }
        
        private void OnValidacion_SUNATOperationCompleted(object arg) {
            if ((this.Validacion_SUNATCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Validacion_SUNATCompleted(this, new Validacion_SUNATCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    public partial class BuscarEmpresaResult {
        
        private DatosEstablecimientoAnexo[] datosEstablecimientoField;
        
        private DatosSecundariosdelContribuyente datosSecundariosField;
        
        private string ddp_ciiuFieldField;
        
        private string ddp_estadoFieldField;
        
        private string ddp_fecactFieldField;
        
        private string ddp_fecaltFieldField;
        
        private string ddp_fecbajFieldField;
        
        private string ddp_flag22FieldField;
        
        private string ddp_identiFieldField;
        
        private string ddp_inter1FieldField;
        
        private string ddp_llltttFieldField;
        
        private string ddp_nombreFieldField;
        
        private string ddp_nomviaFieldField;
        
        private string ddp_nomzonFieldField;
        
        private string ddp_numer1FieldField;
        
        private string ddp_numregFieldField;
        
        private string ddp_numrucFieldField;
        
        private string ddp_refer1FieldField;
        
        private string ddp_resultadoField;
        
        private int ddp_secuenFieldField;
        
        private bool ddp_secuenFieldFieldSpecified;
        
        private string ddp_tipviaFieldField;
        
        private string ddp_tipzonFieldField;
        
        private string ddp_tpoempFieldField;
        
        private string ddp_ubigeoFieldField;
        
        private string desc_tipviaFieldField;
        
        private ListarRepLegales[] representanteslegalesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DatosEstablecimientoAnexo[] DatosEstablecimiento {
            get {
                return this.datosEstablecimientoField;
            }
            set {
                this.datosEstablecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DatosSecundariosdelContribuyente DatosSecundarios {
            get {
                return this.datosSecundariosField;
            }
            set {
                this.datosSecundariosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_ciiuField {
            get {
                return this.ddp_ciiuFieldField;
            }
            set {
                this.ddp_ciiuFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_estadoField {
            get {
                return this.ddp_estadoFieldField;
            }
            set {
                this.ddp_estadoFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_fecactField {
            get {
                return this.ddp_fecactFieldField;
            }
            set {
                this.ddp_fecactFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_fecaltField {
            get {
                return this.ddp_fecaltFieldField;
            }
            set {
                this.ddp_fecaltFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_fecbajField {
            get {
                return this.ddp_fecbajFieldField;
            }
            set {
                this.ddp_fecbajFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_flag22Field {
            get {
                return this.ddp_flag22FieldField;
            }
            set {
                this.ddp_flag22FieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_identiField {
            get {
                return this.ddp_identiFieldField;
            }
            set {
                this.ddp_identiFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_inter1Field {
            get {
                return this.ddp_inter1FieldField;
            }
            set {
                this.ddp_inter1FieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_llltttField {
            get {
                return this.ddp_llltttFieldField;
            }
            set {
                this.ddp_llltttFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_nombreField {
            get {
                return this.ddp_nombreFieldField;
            }
            set {
                this.ddp_nombreFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_nomviaField {
            get {
                return this.ddp_nomviaFieldField;
            }
            set {
                this.ddp_nomviaFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_nomzonField {
            get {
                return this.ddp_nomzonFieldField;
            }
            set {
                this.ddp_nomzonFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_numer1Field {
            get {
                return this.ddp_numer1FieldField;
            }
            set {
                this.ddp_numer1FieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_numregField {
            get {
                return this.ddp_numregFieldField;
            }
            set {
                this.ddp_numregFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_numrucField {
            get {
                return this.ddp_numrucFieldField;
            }
            set {
                this.ddp_numrucFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_refer1Field {
            get {
                return this.ddp_refer1FieldField;
            }
            set {
                this.ddp_refer1FieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_resultado {
            get {
                return this.ddp_resultadoField;
            }
            set {
                this.ddp_resultadoField = value;
            }
        }
        
        /// <remarks/>
        public int ddp_secuenField {
            get {
                return this.ddp_secuenFieldField;
            }
            set {
                this.ddp_secuenFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddp_secuenFieldSpecified {
            get {
                return this.ddp_secuenFieldFieldSpecified;
            }
            set {
                this.ddp_secuenFieldFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_tipviaField {
            get {
                return this.ddp_tipviaFieldField;
            }
            set {
                this.ddp_tipviaFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_tipzonField {
            get {
                return this.ddp_tipzonFieldField;
            }
            set {
                this.ddp_tipzonFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_tpoempField {
            get {
                return this.ddp_tpoempFieldField;
            }
            set {
                this.ddp_tpoempFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_ubigeoField {
            get {
                return this.ddp_ubigeoFieldField;
            }
            set {
                this.ddp_ubigeoFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_tipviaField {
            get {
                return this.desc_tipviaFieldField;
            }
            set {
                this.desc_tipviaFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ListarRepLegales[] representanteslegales {
            get {
                return this.representanteslegalesField;
            }
            set {
                this.representanteslegalesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    public partial class DatosEstablecimientoAnexo {
        
        private int spr_correlFieldField;
        
        private bool spr_correlFieldFieldSpecified;
        
        private string spr_fecactFieldField;
        
        private string spr_inter1FieldField;
        
        private string spr_licencFieldField;
        
        private string spr_nombreFieldField;
        
        private string spr_nomviaFieldField;
        
        private string spr_nomzonFieldField;
        
        private string spr_numer1FieldField;
        
        private string spr_numrucFieldField;
        
        private string spr_refer1FieldField;
        
        private string spr_tipestFieldField;
        
        private string spr_tipviaFieldField;
        
        private string spr_tipzonFieldField;
        
        private string spr_ubigeoFieldField;
        
        /// <remarks/>
        public int spr_correlField {
            get {
                return this.spr_correlFieldField;
            }
            set {
                this.spr_correlFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool spr_correlFieldSpecified {
            get {
                return this.spr_correlFieldFieldSpecified;
            }
            set {
                this.spr_correlFieldFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_fecactField {
            get {
                return this.spr_fecactFieldField;
            }
            set {
                this.spr_fecactFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_inter1Field {
            get {
                return this.spr_inter1FieldField;
            }
            set {
                this.spr_inter1FieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_licencField {
            get {
                return this.spr_licencFieldField;
            }
            set {
                this.spr_licencFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_nombreField {
            get {
                return this.spr_nombreFieldField;
            }
            set {
                this.spr_nombreFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_nomviaField {
            get {
                return this.spr_nomviaFieldField;
            }
            set {
                this.spr_nomviaFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_nomzonField {
            get {
                return this.spr_nomzonFieldField;
            }
            set {
                this.spr_nomzonFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_numer1Field {
            get {
                return this.spr_numer1FieldField;
            }
            set {
                this.spr_numer1FieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_numrucField {
            get {
                return this.spr_numrucFieldField;
            }
            set {
                this.spr_numrucFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_refer1Field {
            get {
                return this.spr_refer1FieldField;
            }
            set {
                this.spr_refer1FieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_tipestField {
            get {
                return this.spr_tipestFieldField;
            }
            set {
                this.spr_tipestFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_tipviaField {
            get {
                return this.spr_tipviaFieldField;
            }
            set {
                this.spr_tipviaFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_tipzonField {
            get {
                return this.spr_tipzonFieldField;
            }
            set {
                this.spr_tipzonFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spr_ubigeoField {
            get {
                return this.spr_ubigeoFieldField;
            }
            set {
                this.spr_ubigeoFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    public partial class ListarRepLegales {
        
        private short num_ord_suceFieldField;
        
        private bool num_ord_suceFieldFieldSpecified;
        
        private string rso_cargooFieldField;
        
        private string rso_docideFieldField;
        
        private string rso_fecactFieldField;
        
        private string rso_fecnacFieldField;
        
        private string rso_nombreFieldField;
        
        private string rso_nrodocFieldField;
        
        private string rso_numrucFieldField;
        
        private string rso_vdesdeFieldField;
        
        /// <remarks/>
        public short num_ord_suceField {
            get {
                return this.num_ord_suceFieldField;
            }
            set {
                this.num_ord_suceFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool num_ord_suceFieldSpecified {
            get {
                return this.num_ord_suceFieldFieldSpecified;
            }
            set {
                this.num_ord_suceFieldFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rso_cargooField {
            get {
                return this.rso_cargooFieldField;
            }
            set {
                this.rso_cargooFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rso_docideField {
            get {
                return this.rso_docideFieldField;
            }
            set {
                this.rso_docideFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rso_fecactField {
            get {
                return this.rso_fecactFieldField;
            }
            set {
                this.rso_fecactFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rso_fecnacField {
            get {
                return this.rso_fecnacFieldField;
            }
            set {
                this.rso_fecnacFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rso_nombreField {
            get {
                return this.rso_nombreFieldField;
            }
            set {
                this.rso_nombreFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rso_nrodocField {
            get {
                return this.rso_nrodocFieldField;
            }
            set {
                this.rso_nrodocFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rso_numrucField {
            get {
                return this.rso_numrucFieldField;
            }
            set {
                this.rso_numrucFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rso_vdesdeField {
            get {
                return this.rso_vdesdeFieldField;
            }
            set {
                this.rso_vdesdeFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    public partial class DatosSecundariosdelContribuyente {
        
        private string dds_asientFieldField;
        
        private string dds_comextFieldField;
        
        private string dds_constiFieldField;
        
        private string dds_contabFieldField;
        
        private string dds_docideFieldField;
        
        private string dds_domiciFieldField;
        
        private string dds_facturFieldField;
        
        private string dds_fecactFieldField;
        
        private string dds_fecnacFieldField;
        
        private string dds_fichaFieldField;
        
        private string dds_inicioFieldField;
        
        private string dds_licencFieldField;
        
        private string dds_nacionFieldField;
        
        private string dds_nfolioFieldField;
        
        private string dds_nomcomFieldField;
        
        private string dds_nrodocFieldField;
        
        private string dds_numfaxFieldField;
        
        private string dds_numrucFieldField;
        
        private string dds_orientFieldField;
        
        private string dds_paispaFieldField;
        
        private string dds_pasapoFieldField;
        
        private string dds_patronFieldField;
        
        private string dds_sexoFieldField;
        
        private string dds_telef1FieldField;
        
        private string dds_telef2FieldField;
        
        private string dds_telef3FieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_asientField {
            get {
                return this.dds_asientFieldField;
            }
            set {
                this.dds_asientFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_comextField {
            get {
                return this.dds_comextFieldField;
            }
            set {
                this.dds_comextFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_constiField {
            get {
                return this.dds_constiFieldField;
            }
            set {
                this.dds_constiFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_contabField {
            get {
                return this.dds_contabFieldField;
            }
            set {
                this.dds_contabFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_docideField {
            get {
                return this.dds_docideFieldField;
            }
            set {
                this.dds_docideFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_domiciField {
            get {
                return this.dds_domiciFieldField;
            }
            set {
                this.dds_domiciFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_facturField {
            get {
                return this.dds_facturFieldField;
            }
            set {
                this.dds_facturFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_fecactField {
            get {
                return this.dds_fecactFieldField;
            }
            set {
                this.dds_fecactFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_fecnacField {
            get {
                return this.dds_fecnacFieldField;
            }
            set {
                this.dds_fecnacFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_fichaField {
            get {
                return this.dds_fichaFieldField;
            }
            set {
                this.dds_fichaFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_inicioField {
            get {
                return this.dds_inicioFieldField;
            }
            set {
                this.dds_inicioFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_licencField {
            get {
                return this.dds_licencFieldField;
            }
            set {
                this.dds_licencFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_nacionField {
            get {
                return this.dds_nacionFieldField;
            }
            set {
                this.dds_nacionFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_nfolioField {
            get {
                return this.dds_nfolioFieldField;
            }
            set {
                this.dds_nfolioFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_nomcomField {
            get {
                return this.dds_nomcomFieldField;
            }
            set {
                this.dds_nomcomFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_nrodocField {
            get {
                return this.dds_nrodocFieldField;
            }
            set {
                this.dds_nrodocFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_numfaxField {
            get {
                return this.dds_numfaxFieldField;
            }
            set {
                this.dds_numfaxFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_numrucField {
            get {
                return this.dds_numrucFieldField;
            }
            set {
                this.dds_numrucFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_orientField {
            get {
                return this.dds_orientFieldField;
            }
            set {
                this.dds_orientFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_paispaField {
            get {
                return this.dds_paispaFieldField;
            }
            set {
                this.dds_paispaFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_pasapoField {
            get {
                return this.dds_pasapoFieldField;
            }
            set {
                this.dds_pasapoFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_patronField {
            get {
                return this.dds_patronFieldField;
            }
            set {
                this.dds_patronFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_sexoField {
            get {
                return this.dds_sexoFieldField;
            }
            set {
                this.dds_sexoFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_telef1Field {
            get {
                return this.dds_telef1FieldField;
            }
            set {
                this.dds_telef1FieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_telef2Field {
            get {
                return this.dds_telef2FieldField;
            }
            set {
                this.dds_telef2FieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dds_telef3Field {
            get {
                return this.dds_telef3FieldField;
            }
            set {
                this.dds_telef3FieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void BuscarSunatProduccionParametroCompletedEventHandler(object sender, BuscarSunatProduccionParametroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarSunatProduccionParametroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarSunatProduccionParametroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BuscarEmpresaResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BuscarEmpresaResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Validacion_SUNATCompletedEventHandler(object sender, Validacion_SUNATCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Validacion_SUNATCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Validacion_SUNATCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BuscarEmpresaResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BuscarEmpresaResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591