//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace WebApplication.ServiceSunat {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HttpSistemasService", Namespace="http://tempuri.org/")]
    public partial class WCFSistemasService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarSunatProduccionParametroOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WCFSistemasService() {
            this.Url = global::WebApplication.Properties.Settings.Default.WebApplication_ServiceSunat_WCFSistemasService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarSunatProduccionParametroCompletedEventHandler BuscarSunatProduccionParametroCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWCFSistemasService/BuscarSunatProduccionParametro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BuscarEmpresaResult BuscarSunatProduccionParametro([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ID_RUC) {
            object[] results = this.Invoke("BuscarSunatProduccionParametro", new object[] {
                        ID_RUC});
            return ((BuscarEmpresaResult)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarSunatProduccionParametroAsync(string ID_RUC) {
            this.BuscarSunatProduccionParametroAsync(ID_RUC, null);
        }
        
        /// <remarks/>
        public void BuscarSunatProduccionParametroAsync(string ID_RUC, object userState) {
            if ((this.BuscarSunatProduccionParametroOperationCompleted == null)) {
                this.BuscarSunatProduccionParametroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarSunatProduccionParametroOperationCompleted);
            }
            this.InvokeAsync("BuscarSunatProduccionParametro", new object[] {
                        ID_RUC}, this.BuscarSunatProduccionParametroOperationCompleted, userState);
        }
        
        private void OnBuscarSunatProduccionParametroOperationCompleted(object arg) {
            if ((this.BuscarSunatProduccionParametroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarSunatProduccionParametroCompleted(this, new BuscarSunatProduccionParametroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFSistemasService")]
    public partial class BuscarEmpresaResult {
        
        private string cod_depFieldField;
        
        private string cod_distFieldField;
        
        private string cod_provFieldField;
        
        private string ddp_ciiuFieldField;
        
        private string ddp_dobleFieldField;
        
        private string ddp_estadoFieldField;
        
        private string ddp_fecactFieldField;
        
        private string ddp_fecaltFieldField;
        
        private string ddp_fecbajFieldField;
        
        private string ddp_flag22FieldField;
        
        private string ddp_identiFieldField;
        
        private string ddp_inter1FieldField;
        
        private string ddp_llltttFieldField;
        
        private string ddp_mclaseFieldField;
        
        private string ddp_nombreFieldField;
        
        private string ddp_nomviaFieldField;
        
        private string ddp_nomzonFieldField;
        
        private string ddp_numer1FieldField;
        
        private string ddp_numregFieldField;
        
        private string ddp_numrucFieldField;
        
        private string ddp_reactiFieldField;
        
        private string ddp_refer1FieldField;
        
        private int ddp_secuenFieldField;
        
        private bool ddp_secuenFieldFieldSpecified;
        
        private string ddp_tamanoFieldField;
        
        private string ddp_tipviaFieldField;
        
        private string ddp_tipzonFieldField;
        
        private string ddp_tpoempFieldField;
        
        private string ddp_ubigeoFieldField;
        
        private string ddp_usernaFieldField;
        
        private string desc_ciiuFieldField;
        
        private string desc_depFieldField;
        
        private string desc_distFieldField;
        
        private string desc_estadoFieldField;
        
        private string desc_flag22FieldField;
        
        private string desc_identiFieldField;
        
        private string desc_numregFieldField;
        
        private string desc_provFieldField;
        
        private string desc_tamanoFieldField;
        
        private string desc_tipviaFieldField;
        
        private string desc_tipzonFieldField;
        
        private string desc_tpoempFieldField;
        
        private bool esActivoFieldField;
        
        private bool esActivoFieldFieldSpecified;
        
        private bool esHabidoFieldField;
        
        private bool esHabidoFieldFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cod_depField {
            get {
                return this.cod_depFieldField;
            }
            set {
                this.cod_depFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cod_distField {
            get {
                return this.cod_distFieldField;
            }
            set {
                this.cod_distFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cod_provField {
            get {
                return this.cod_provFieldField;
            }
            set {
                this.cod_provFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_ciiuField {
            get {
                return this.ddp_ciiuFieldField;
            }
            set {
                this.ddp_ciiuFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_dobleField {
            get {
                return this.ddp_dobleFieldField;
            }
            set {
                this.ddp_dobleFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_estadoField {
            get {
                return this.ddp_estadoFieldField;
            }
            set {
                this.ddp_estadoFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_fecactField {
            get {
                return this.ddp_fecactFieldField;
            }
            set {
                this.ddp_fecactFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_fecaltField {
            get {
                return this.ddp_fecaltFieldField;
            }
            set {
                this.ddp_fecaltFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_fecbajField {
            get {
                return this.ddp_fecbajFieldField;
            }
            set {
                this.ddp_fecbajFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_flag22Field {
            get {
                return this.ddp_flag22FieldField;
            }
            set {
                this.ddp_flag22FieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_identiField {
            get {
                return this.ddp_identiFieldField;
            }
            set {
                this.ddp_identiFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_inter1Field {
            get {
                return this.ddp_inter1FieldField;
            }
            set {
                this.ddp_inter1FieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_llltttField {
            get {
                return this.ddp_llltttFieldField;
            }
            set {
                this.ddp_llltttFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_mclaseField {
            get {
                return this.ddp_mclaseFieldField;
            }
            set {
                this.ddp_mclaseFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_nombreField {
            get {
                return this.ddp_nombreFieldField;
            }
            set {
                this.ddp_nombreFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_nomviaField {
            get {
                return this.ddp_nomviaFieldField;
            }
            set {
                this.ddp_nomviaFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_nomzonField {
            get {
                return this.ddp_nomzonFieldField;
            }
            set {
                this.ddp_nomzonFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_numer1Field {
            get {
                return this.ddp_numer1FieldField;
            }
            set {
                this.ddp_numer1FieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_numregField {
            get {
                return this.ddp_numregFieldField;
            }
            set {
                this.ddp_numregFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_numrucField {
            get {
                return this.ddp_numrucFieldField;
            }
            set {
                this.ddp_numrucFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_reactiField {
            get {
                return this.ddp_reactiFieldField;
            }
            set {
                this.ddp_reactiFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_refer1Field {
            get {
                return this.ddp_refer1FieldField;
            }
            set {
                this.ddp_refer1FieldField = value;
            }
        }
        
        /// <comentarios/>
        public int ddp_secuenField {
            get {
                return this.ddp_secuenFieldField;
            }
            set {
                this.ddp_secuenFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddp_secuenFieldSpecified {
            get {
                return this.ddp_secuenFieldFieldSpecified;
            }
            set {
                this.ddp_secuenFieldFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_tamanoField {
            get {
                return this.ddp_tamanoFieldField;
            }
            set {
                this.ddp_tamanoFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_tipviaField {
            get {
                return this.ddp_tipviaFieldField;
            }
            set {
                this.ddp_tipviaFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_tipzonField {
            get {
                return this.ddp_tipzonFieldField;
            }
            set {
                this.ddp_tipzonFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_tpoempField {
            get {
                return this.ddp_tpoempFieldField;
            }
            set {
                this.ddp_tpoempFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_ubigeoField {
            get {
                return this.ddp_ubigeoFieldField;
            }
            set {
                this.ddp_ubigeoFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ddp_usernaField {
            get {
                return this.ddp_usernaFieldField;
            }
            set {
                this.ddp_usernaFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_ciiuField {
            get {
                return this.desc_ciiuFieldField;
            }
            set {
                this.desc_ciiuFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_depField {
            get {
                return this.desc_depFieldField;
            }
            set {
                this.desc_depFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_distField {
            get {
                return this.desc_distFieldField;
            }
            set {
                this.desc_distFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_estadoField {
            get {
                return this.desc_estadoFieldField;
            }
            set {
                this.desc_estadoFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_flag22Field {
            get {
                return this.desc_flag22FieldField;
            }
            set {
                this.desc_flag22FieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_identiField {
            get {
                return this.desc_identiFieldField;
            }
            set {
                this.desc_identiFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_numregField {
            get {
                return this.desc_numregFieldField;
            }
            set {
                this.desc_numregFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_provField {
            get {
                return this.desc_provFieldField;
            }
            set {
                this.desc_provFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_tamanoField {
            get {
                return this.desc_tamanoFieldField;
            }
            set {
                this.desc_tamanoFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_tipviaField {
            get {
                return this.desc_tipviaFieldField;
            }
            set {
                this.desc_tipviaFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_tipzonField {
            get {
                return this.desc_tipzonFieldField;
            }
            set {
                this.desc_tipzonFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_tpoempField {
            get {
                return this.desc_tpoempFieldField;
            }
            set {
                this.desc_tpoempFieldField = value;
            }
        }
        
        /// <comentarios/>
        public bool esActivoField {
            get {
                return this.esActivoFieldField;
            }
            set {
                this.esActivoFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esActivoFieldSpecified {
            get {
                return this.esActivoFieldFieldSpecified;
            }
            set {
                this.esActivoFieldFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool esHabidoField {
            get {
                return this.esHabidoFieldField;
            }
            set {
                this.esHabidoFieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esHabidoFieldSpecified {
            get {
                return this.esHabidoFieldFieldSpecified;
            }
            set {
                this.esHabidoFieldFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BuscarSunatProduccionParametroCompletedEventHandler(object sender, BuscarSunatProduccionParametroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarSunatProduccionParametroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarSunatProduccionParametroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BuscarEmpresaResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BuscarEmpresaResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591